
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/employeemanager
    username: root
    password: root

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: create-drop
    open-in-view: off
    show-sql: true

application:
  jwt:
    secret-key: MyVeryStrongPasswordIsBatmanFightingAgainstCatwomanAndWithJokerWithHarleyQuinnAndHerPrettyFaceAndStrongHammer
    token-prefix: "Bearer "
    token-expiration-after-days: 10